test/crimson/seastore/test_seastore.cc: should not return a value
clang++-14:

```
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/crimson/seastore/test_seastore.cc:86:5: error: void function 'do_transaction' should not return a value [-Wreturn-type]
    return sharded_seastore->do_transaction(
    ^      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/crimson/seastore/test_seastore.cc:94:5: error: void function 'set_meta' should not return a value [-Wreturn-type]
    return seastore->write_meta(key, value).get();
    ^      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.
```

Signed-off-by: Matan Breizman <mbreizma@redhat.com>
(cherry picked from commit 28a7ee81280073eb387ea3b7c8de5204be45f453)