pybind/mgr/mgr_util: convert certs to bytes before loading them
This function expects to be passed bytes rather than a string.
Mypy complains about failing to do this conversion

mgr_util.py: note: In function "verify_cacrt_content":
mgr_util.py:547: error: Argument 2 to "load_certificate" has incompatible type "str"; expected "bytes"
mgr_util.py: note: In function "verify_tls":
mgr_util.py:584: error: Argument 2 to "load_certificate" has incompatible type "str"; expected "bytes"

Signed-off-by: Adam King <adking@redhat.com>
(cherry picked from commit 3b66176507ed32dde1727fc45a793062ddf4dc30)