erasure-code/clay: cleanup unused but set variable count_retrieved_sub_chunks
Addresses clang 17 error:

	/home/rocky/ceph/src/erasure-code/clay/ErasureCodeClay.cc:481:7: error: variable 'count_retrieved_sub_chunks' set but not used [-Werror,-Wunused-but-set-variable]

Signed-off-by: kshtsk <kyrylo.shatskyy@clyso.com>