ceph-volume: address mypy errors in disk.py
typical error:

```
ceph_volume/util/disk.py:1374: error: Incompatible types in assignment (expression has type "Optional[str]", variable has type "str")  [assignment]
```

This commits addresses it.

Signed-off-by: Guillaume Abrioux <gabrioux@ibm.com>
(cherry picked from commit b5e7008d28a5acd63ea9cd0c6b27f400dad409af)